// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.21;

import {ManagerWithMerkleVerification} from "src/base/Roles/ManagerWithMerkleVerification.sol";
import {CreateDnEnaPtHedgeLeafsScript} from "script/MerkleRootCreation/CreateDnEnaPtHedgeLeafs.s.sol";

import "forge-std/console.sol";

/**
 * @notice Safe-multisig variant for DN PT-sENA HyperEVM leaves.
 *         Regenerates the HyperEVM leaf file and writes a Safe Transaction Builder batch that updates
 *         the strategist manage root. This script does not broadcast and does not need a private key.
 *
 * Run:
 *   HYPEREVM_RPC_URL=https://rpc.hyperliquid.xyz/evm forge script \
 *     script/MerkleRootCreation/HyperEvm/CreateDnEnaPtHedgeLeafsSafe.s.sol:CreateDnEnaPtHedgeLeafsSafeScript \
 *     --rpc-url https://rpc.hyperliquid.xyz/evm -vvvv
 *
 * Outputs:
 *   - ./leafs/HyperEvm/DnPtSenaLeafs.json
 *   - ./leafs/HyperEvm/DnPtSenaSafeBatch.json
 */
contract CreateDnEnaPtHedgeLeafsSafeScript is CreateDnEnaPtHedgeLeafsScript {
    address internal constant STRATEGIST = 0xc77A0D038b0e3F900DD222cF8343675DCCdB01c1;
    uint256 internal constant HYPEREVM_CHAIN_ID = 999;

    function run() external override {
        generateHyperEvmLeafs();

        string memory leafPath = "./leafs/HyperEvm/DnPtSenaLeafs.json";
        bytes32 newRoot = vm.parseJsonBytes32(vm.readFile(leafPath), ".metadata.ManageRoot");

        address[] memory tos = new address[](1);
        bytes[] memory datas = new bytes[](1);
        string[] memory labels = new string[](1);

        tos[0] = hyperEvmManagerAddress;
        datas[0] = abi.encodeWithSelector(ManagerWithMerkleVerification.setManageRoot.selector, STRATEGIST, newRoot);
        labels[0] = "manager.setManageRoot(strategist, newRoot)";

        console.log("=== new HyperEVM manage root ===");
        console.logBytes32(newRoot);
        console.log("=== Safe transactions (chainId 999, value 0) ===");
        for (uint256 i; i < tos.length; ++i) {
            console.log(labels[i]);
            console.log("  to:");
            console.logAddress(tos[i]);
            console.log("  data:");
            console.logBytes(datas[i]);
        }

        _writeSafeBatch(tos, datas);
    }

    function _writeSafeBatch(address[] memory tos, bytes[] memory datas) internal {
        string memory txs = "";
        for (uint256 i; i < tos.length; ++i) {
            string memory one = string.concat(
                '{"to":"',
                vm.toString(tos[i]),
                '","value":"0","data":"',
                vm.toString(datas[i]),
                '","contractMethod":null,"contractInputsValues":null}'
            );
            txs = i == 0 ? one : string.concat(txs, ",", one);
        }

        string memory batch = string.concat(
            '{"version":"1.0","chainId":"',
            vm.toString(HYPEREVM_CHAIN_ID),
            '","createdAt":',
            vm.toString(block.timestamp * 1000),
            ',"meta":{"name":"DN PT-sENA: update HyperEVM manage root",',
            '"description":"Generated by CreateDnEnaPtHedgeLeafsSafe.s.sol"},"transactions":[',
            txs,
            "]}"
        );

        string memory outPath = "./leafs/HyperEvm/DnPtSenaSafeBatch.json";
        vm.writeFile(outPath, batch);
        console.log("Wrote Safe Transaction Builder batch:");
        console.log(outPath);
    }
}
